# apply()

- 함수를 특정 단위로 쉽게 사용할 수 있도록 지원하는 함수
    - apply계열 함수들의 차이점 : 입력 데이터의 종류, 결과의 형태, 연산 단위

## apply함수의 문법
- apply(함수를 적용할 대상, 방향, 함수)

In [1]:
a <- array(1:12, dim= c(3,4))
print(a)

     [,1] [,2] [,3] [,4]
[1,]    1    4    7   10
[2,]    2    5    8   11
[3,]    3    6    9   12


## 적용방향

- 1 : 가로
- 2 : 세로
<img src ="./img/2d_apply.jpg">

In [2]:
apply(a,1,max)

[1] 10 11 12

In [3]:
apply(a,2,max)

[1]  3  6  9 12

In [4]:
# 적용할 함수 작성하기
#"^"는 제곱이란 뜻
f <- function(vec){
    max(vec)^2 +3
}

In [5]:
apply(a,1,f)

# ex)10제곱에 +3 103

[1] 103 124 147

## 3차원 array에 적용

<img src = "./img/3d_apply_1.jpg" width = 500 height = 500>
- 3차원 데이터 가로
<img src = "./img/3d_apply_2.jpg" width = 500 height = 500>
- 3차원 데이터 세로

In [6]:
a <- array(1:24, dim = c(3,4,2))
print(a)

, , 1

     [,1] [,2] [,3] [,4]
[1,]    1    4    7   10
[2,]    2    5    8   11
[3,]    3    6    9   12

, , 2

     [,1] [,2] [,3] [,4]
[1,]   13   16   19   22
[2,]   14   17   20   23
[3,]   15   18   21   24



In [7]:
# 3차원배열 가로로 잘랐음
apply(a,1,max)

[1] 22 23 24

In [8]:
# 3차원배열 세로로 잘랐음
apply(a,2,max)

[1] 15 18 21 24

In [9]:
a <- array(sample(24,24), dim = c(3,4,2))
print(a)

, , 1

     [,1] [,2] [,3] [,4]
[1,]   13    6   11    5
[2,]   10   18   22   23
[3,]    3    2   14   15

, , 2

     [,1] [,2] [,3] [,4]
[1,]    7    8   21    4
[2,]   20   12    9   16
[3,]   19   17    1   24



In [10]:
apply(a,1,max)

[1] 21 23 24

In [11]:
# 3 : 레이어 별로 적용
apply(a,3,max)

[1] 23 24

In [12]:
a[2,4,1] <- NA
a[2,1,1] <- NA

In [17]:
print(a)

, , 1

     [,1] [,2] [,3] [,4]
[1,]   13    6   11    5
[2,]   NA   18   22   NA
[3,]    3    2   14   15

, , 2

     [,1] [,2] [,3] [,4]
[1,]    7    8   21    4
[2,]   20   12    9   16
[3,]   19   17    1   24



In [14]:
# 2번째 열에 na값이 있어서 결과가 나오지 않는다.
apply(a,1,mean)

[1]  9.375     NA 11.875

In [15]:
apply(a,2,mean)

[1]   NA 10.5 13.0   NA

In [16]:
apply(a,1,mean,na.rm = T)

[1]  9.37500 16.16667 11.87500

# lapply

- list + apply
- 실행 결과가 list형태로 출력

In [18]:
lapply(a, function(x){x*2})

[[1]]
[1] 26

[[2]]
[1] NA

[[3]]
[1] 6

[[4]]
[1] 12

[[5]]
[1] 36

[[6]]
[1] 4

[[7]]
[1] 22

[[8]]
[1] 44

[[9]]
[1] 28

[[10]]
[1] 10

[[11]]
[1] NA

[[12]]
[1] 30

[[13]]
[1] 14

[[14]]
[1] 40

[[15]]
[1] 38

[[16]]
[1] 16

[[17]]
[1] 24

[[18]]
[1] 34

[[19]]
[1] 42

[[20]]
[1] 18

[[21]]
[1] 2

[[22]]
[1] 8

[[23]]
[1] 32

[[24]]
[1] 48

# sapply

- lapply에서 사용자 편의성을 고려한 함수
- 기본적으로는 벡터형태로 출력
    - 입력데이터가 리스트 형태인 경우 리스트로 출력
    - simplify = F인 경우 리스트 형태로 출력

In [19]:
sapply(a, function(x){x*2},simplify = F)

[[1]]
[1] 26

[[2]]
[1] NA

[[3]]
[1] 6

[[4]]
[1] 12

[[5]]
[1] 36

[[6]]
[1] 4

[[7]]
[1] 22

[[8]]
[1] 44

[[9]]
[1] 28

[[10]]
[1] 10

[[11]]
[1] NA

[[12]]
[1] 30

[[13]]
[1] 14

[[14]]
[1] 40

[[15]]
[1] 38

[[16]]
[1] 16

[[17]]
[1] 24

[[18]]
[1] 34

[[19]]
[1] 42

[[20]]
[1] 18

[[21]]
[1] 2

[[22]]
[1] 8

[[23]]
[1] 32

[[24]]
[1] 48